#!/usr/bin/bash
# SPDX-License-Identifier: GNU General Public License v2.0 only
# Copyright (c) 2026 Juan Diluca
# See the LICENSE file in the repository root for details.

psql \
	-U postgres \
	-d discogs \
	-c \
	'
	create or replace function xs01alias(
		artistid integer
	)
	returns table(
		artist_id integer,
		artist_name text,
		artist_realname text,
		alias_name text
	)
	as $$
	begin
	return query
		select
			xa.artist_id,
			xa.artist_name,
			xa.artist_realname,
			xk.alias_name
		from
			(
			select
				n.artist_id,
				n.artist_name,
				n.artist_realname
			from
				xz01artist(
					artistid
				) n
			) xa

		left join

			(
			select
				n.artist_id,
				n.alias_name
			from
				artist_alias n
			) xk
		on
			xa.artist_id = xk.artist_id
		order by
			xk.alias_name
		;
	end;
	$$ language plpgsql;
	'
