#!/usr/bin/bash
# SPDX-License-Identifier: GNU General Public License v2.0 only
# Copyright (c) 2026 Juan Diluca
# See the LICENSE file in the repository root for details.

psql \
	-U postgres \
	-d discogs \
	-c \
	'
	create or replace function xs02master(
		artistid integer
	)
	returns table(
		artist_id integer,
		artist_name text,
		master_id integer,
		master_title text,
		master_year integer,
		master_data_quality text
	)
	as $$
	begin
	return query
		select
			n.artist_id,
			n.artist_name,
			n.master_id,
			n.master_title,
			n.master_year,
			n.master_data_quality
		from
			xz02master(
				artistid
			) n
		order by
			n.master_year,
			n.master_id
		;
	end;
	$$ language plpgsql;
	'
