#!/usr/bin/bash
# SPDX-License-Identifier: GNU General Public License v2.0 only
# Copyright (c) 2026 Juan Diluca
# See the LICENSE file in the repository root for details.

psql \
	-U postgres \
	-d discogs \
	-c \
	'
	create or replace function xz02master(
		artistid integer
	)
	returns table(
		artist_id integer,
		artist_name text,
		master_id integer,
		master_title text,
		master_year integer,
		master_data_quality text
	)
	as $$
	begin
	return query
		select
			xam.artist_id,
			xam.artist_name,
			xmm.master_id,
			xmm.master_title,
			xmm.master_year,
			xmm.master_data_quality
		from
			(
			select
				xa.artist_id,
				xa.artist_name,
				xm.master_id
			from
				(
				select
					n.artist_id,
					n.artist_name
				from
					xz01artist(
						artistid
					) n
				) xa

			left join

				(
				select
					n.artist_id,
					n.master_id
				from
					master_artist n
				) xm
			on
				xa.artist_id = xm.artist_id
			) xam

		left join

			(
			select
				n.id as master_id,
				n.title as master_title,
				n.year as master_year,
				n.data_quality as master_data_quality
			from
				master n
			) xmm
		on
			xam.master_id = xmm.master_id
		;
	end;
	$$ language plpgsql;
	'
