#!/usr/bin/bash
# SPDX-License-Identifier: GNU General Public License v2.0 only
# Copyright (c) 2026 Juan Diluca
# See the LICENSE file in the repository root for details.

psql \
	-U postgres \
	-d discogs \
	-c \
	'
	create or replace function xz03no_master_release_x(
		artistid integer
	)
	returns table(
		artist_id integer,
		artist_name text,
		artist_name_release text,
		release_id integer,
		extra integer,
		anv text,
		position_artist integer,
		role text,
		join_string text,
		release_title text,
		release_date text,
		release_country text,
		release_data_quality text
	)
	as $$
	begin
	return query
		select
			xar.artist_id,
			xar.artist_name,
			xar.artist_name_release,
			xrr.release_id,
			xar.extra,
			xar.anv,
			xar.position_artist,
			xar.role,
			xar.join_string,
			xrr.release_title,
			xrr.release_date,
			xrr.release_country,
			xrr.release_data_quality
		from
			(
			select
				xa.artist_id,
				xa.artist_name,
				xr.artist_name_release,
				xr.release_id,
				xr.extra,
				xr.anv,
				xr.position_artist,
				xr.role,
				xr.join_string
			from
				(
				select
					n.artist_id,
					n.artist_name
				from
					xz01artist(
						artistid
					) n
				) xa

			left join

				(
				select
					n.artist_id,
					n.artist_name as artist_name_release,
					n.release_id,
					n.extra,
					n.anv,
					n.position_artist,
					n.role,
					n.join_string
				from
					xza0release_unique(
						artistid
					) n
				) xr
			on
				xa.artist_id = xr.artist_id
			) xar

		inner join

			(
			select
				n.release_id,
				n.release_title,
				n.release_date,
				n.release_country,
				n.release_data_quality
			from
				xz11release(0) n
			) xrr
		on
			xar.release_id = xrr.release_id
		order by
			xrr.release_id
		;
	end;
	$$ language plpgsql;
	'
