#!/usr/bin/bash
# SPDX-License-Identifier: GNU General Public License v2.0 only
# Copyright (c) 2026 Juan Diluca
# See the LICENSE file in the repository root for details.

psql \
	-U postgres \
	-d discogs \
	-c \
	'
	create or replace function xz05tracklist_xx(
		artistid integer
	)
	returns table(
		artist_id integer,
		artist_name text,
		master_id integer,
		master_title text,
		master_year integer,
		master_data_quality text,
		release_id integer,
		release_title text,
		release_date text,
		release_country text,
		release_data_quality text,
		release_format text,
		release_descriptions text,
		text_string text,
		label_id integer,
		label_name text,
		catno text,
		tracknumber text,
		sequence integer,
		title text,
		duration text,
		parent text
	)
	as $$
	begin
	return query
		select
			vr.artist_id,
			vr.artist_name,
			vr.master_id,
			vr.master_title,
			vr.master_year,
			vr.master_data_quality,
			vr.release_id,
			vr.release_title,
			vr.release_date,
			vr.release_country,
			vr.release_data_quality,
			vr.release_format,
			vr.release_descriptions,
			vr.text_string,
			vr.label_id,
			vr.label_name,
			vr.catno,
			rt.tracknumber,
			rt.sequence,
			rt.title,
			rt.duration,
			rt.parent
		from
			(
			select
				n.artist_id,
				n.artist_name,
				n.master_id,
				n.master_title,
				n.master_year,
				n.master_data_quality,
				n.release_id,
				n.release_title,
				n.release_date,
				n.release_country,
				n.release_data_quality,
				n.release_format,
				n.release_descriptions,
				n.text_string,
				n.label_id,
				n.label_name,
				n.catno
			from
				xz04format_xx(
					artistid
					) n
			) vr

		left join

			(
			select
				n.release_id,
				n.position as tracknumber,
				n.sequence,
				n.title,
				n.duration,
				n.parent
			from
				release_track n
			) rt
		on
			vr.release_id = rt.release_id
		order by
			vr.master_year,
			vr.master_id,
			vr.release_date,
			vr.release_id,
			vr.label_id,
			vr.catno,
			rt.sequence
		;
	end;
	$$ language plpgsql;
	'
