#!/usr/bin/bash
# SPDX-License-Identifier: GNU General Public License v2.0 only
# Copyright (c) 2026 Juan Diluca
# See the LICENSE file in the repository root for details.

psql \
	-U postgres \
	-d discogs \
	-c \
	'
	create or replace function xz23master(
		artistid integer
	)
	returns table(
		artist_id integer,
		master_id integer,
		artist_name text,
		title text,
		year integer,
		data_quality text,
		anv text,
		pos integer,
		join_string text,
		role text
	)
	as $$
	begin
	return query
		select
			nxs.artist_id,
			nxs.master_id,
			nxs.artist_name,
			tfx.title,
			tfx.year,
			tfx.data_quality,
			nxs.anv,
			nxs.pos,
			nxs.join_string,
			nxs.role
		from
			(
			select
				nx.artist_id,
				nx.master_id,
				nx.artist_name,
				nx.anv,
				nx.position as pos,
				nx.join_string,
				nx.role
			from
				master_artist nx
			where
				nx.master_id in
					(
					select
						n.master_id
					from
						xz22master(
							artistid
						) n
					where
						n.mastercount > 1
					)
			) nxs

		left join

			(
			select
				n.id,
				n.title,
				n.year,
				n.data_quality
			from
				master n
			) tfx

		on
			nxs.master_id = tfx.id
		order by
			tfx.year,
			nxs.master_id,
			nxs.pos
		;
	end;
	$$ language plpgsql;
	'
