#!/usr/bin/bash
# SPDX-License-Identifier: GNU General Public License v2.0 only
# Copyright (c) 2026 Juan Diluca
# See the LICENSE file in the repository root for details.

psql \
	-U postgres \
	-d discogs \
	-c \
	'
	create or replace function xz33no_master_release_x1(
		artistid integer
	)
	returns table(
		artist_id integer,
		artist_name text,
		artist_name_release text,
		release_id integer,
		extra integer,
		anv text,
		position_artist integer,
		role text,
		join_string text,
		release_title text,
		release_date text,
		release_country text,
		release_data_quality text,
		releasecount bigint,
		releasecount_artist bigint
	)
	as $$
	begin
	return query
		select
			n.artist_id,
			n.artist_name,
			n.artist_name_release,
			n.release_id,
			n.extra,
			n.anv,
			n.position_artist,
			n.role,
			n.join_string,
			n.release_title,
			n.release_date,
			n.release_country,
			n.release_data_quality,
			n.releasecount,
			n.releasecount_artist
		from
			xz33no_master_release_x(
				artistid
			) n
		where
			n.releasecount = 1
		;
	end;
	$$ language plpgsql;
	'
