#!/usr/bin/bash
# SPDX-License-Identifier: GNU General Public License v2.0 only
# Copyright (c) 2026 Juan Diluca
# See the LICENSE file in the repository root for details.

psql \
	-U postgres \
	-d discogs \
	-c \
	'
	create or replace function xz33no_master_release_x(
		artistid integer
	)
	returns table(
		artist_id integer,
		artist_name text,
		artist_name_release text,
		release_id integer,
		extra integer,
		anv text,
		position_artist integer,
		role text,
		join_string text,
		release_title text,
		release_date text,
		release_country text,
		release_data_quality text,
		releasecount bigint,
		releasecount_artist bigint
	)
	as $$
	begin
	return query
		select
			xrq.artist_id,
			xrq.artist_name,
			xrq.artist_name_release,
			xrq.release_id,
			xrq.extra,
			xrq.anv,
			xrq.position_artist,
			xrq.role,
			xrq.join_string,
			xrq.release_title,
			xrq.release_date,
			xrq.release_country,
			xrq.release_data_quality,
			xrq.releasecount,
			xqq.releasecount_artist
		from
			(
			select
				xr.artist_id,
				xr.artist_name,
				xr.artist_name_release,
				xr.release_id,
				xr.extra,
				xr.anv,
				xr.position_artist,
				xr.role,
				xr.join_string,
				xr.release_title,
				xr.release_date,
				xr.release_country,
				xr.release_data_quality,
				xq.releasecount
			from
				(
				select
					n.artist_id,
					n.artist_name,
					n.artist_name_release,
					n.release_id,
					n.extra,
					n.anv,
					n.position_artist,
					n.role,
					n.join_string,
					n.release_title,
					n.release_date,
					n.release_country,
					n.release_data_quality
				from
					xz03no_master_release_x(
						artistid
					) n
				) xr

			left join

				(
				select
					n.release_id,
					count(n.release_id) as releasecount
				from
					release_artist n
				where
					n.release_id in (
						select
							n.release_id
						from
							xz03no_master_release_x(
								artistid
								) n
						)
					and n.extra = 0
				group by
					n.release_id
				order by
					n.release_id
				) xq
			on
				xr.release_id = xq.release_id
			) xrq

		left join

			(
			select
				n.artist_id,
				n.release_id,
				count(n.release_id) as releasecount_artist
			from
				release_artist n
			where
				n.release_id in (
					select
						n.release_id
					from
						xz03no_master_release_x(
							artistid
							) n
					)
				and n.extra = 0
			group by
				n.artist_id,
				n.release_id
			order by
				n.artist_id,
				n.release_id
			) xqq
		on
			xrq.artist_id = xqq.artist_id
			and xrq.release_id = xqq.release_id
		order by
			xrq.release_date,
			xrq.release_id
		;
	end;
	$$ language plpgsql;
	'
