#!/usr/bin/bash
# SPDX-License-Identifier: GNU General Public License v2.0 only
# Copyright (c) 2026 Juan Diluca
# See the LICENSE file in the repository root for details.

psql \
	-U postgres \
	-d discogs \
	-c \
	'
	create or replace function xza0release_unique(
		artistid integer
	)
	returns table(
		artist_id integer,
		artist_name text,
		release_id integer,
		extra integer,
		anv text,
		position_artist integer,
		role text,
		join_string text
	)
	as $$
	begin
	return query
		select
			n.artist_id,
			n.artist_name,
			n.release_id,
			n.extra,
			n.anv,
			n.position as position_artist,
			n.role,
			n.join_string
		from
			release_artist n
		where
			n.artist_id = artistid
			and n.extra = 0
		;
	end;
	$$ language plpgsql;
	'
